port: 8000
max_retry: 3
timeout: 20
# CORS
origins: 
  - 'http://localhost:*'
  - 'https://localhost:*'
# limit of per minute
limit: 10
# encryption obfuscation (not use recently)
salt: chatgpt
tokens: 
  - test
# api key (random select)
keys:
  - sk-xxx
